steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - -c
      - |
        docker build -t europe-southwest1-docker.pkg.dev/tienda-microservices-459210/image-registry/orders-ms -f dockerfile.prod --platform=linux/amd64 --build-arg ORDERS_DATABASE_URL=$$DATABASE_URL .
    secretEnv: ['DATABASE_URL']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'europe-southwest1-docker.pkg.dev/tienda-microservices-459210/image-registry/orders-ms',
      ]

availableSecrets:
  secretManager:
    - versionName: projects/27116204466/secrets/orders_database_url/versions/1
      env: 'DATABASE_URL'
